[workspace]
members = [
    "src/QirTools/pyqir",
    "src/QirTools/qirlib",
    "src/QirTools/qirlib/microsoft-quantum-qir-runtime-sys",
    "src/QirTools/qirlib/microsoft-quantum-qir-qsharp-foundation-sys",
]
